# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ga_tracking_code: <%= ENV["GA_TRACKING_CODE"] %>
  ga_domain_name: <%= ENV["GA_DOMAIN_NAME"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  oauth_facebook_key: <%= ENV["OAUTH_FACEBOOK_KEY"] %>
  oauth_facebook_secret: <%= ENV["OAUTH_FACEBOOK_SECRET"] %>
  oauth_twitter_key: <%= ENV["OAUTH_TWITTER_KEY"] %>
  oauth_twitter_secret: <%= ENV["OAUTH_TWITTER_SECRET"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
